name: Playground CNCF - Deploy
jobs:
  cncf-playground-rollout:
    name: Update Meshery on CNCF playground
    if: github.repository == 'pyk3dz9s9l/meshery'
    runs-on: ubuntu-24.04
    steps:
    - name: Pull latest images and restart containers
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.OCI_BASTION_HOST }}
        username: ${{ secrets.OCI_BASTION_USERNAME }}
        key: ${{ secrets.OCI_BASTION_KEY }}
        script: |
          kubectl config use-context prod
          kubectl -n meshery set image deployment/playground meshery=${{ inputs.image }}
env:
  GERALT_SECRET: ${{ secrets.GERALT }}
on:
  workflow_call:
    inputs:
      image:
        type: string
        default: playground-latest
  workflow_dispatch:
    inputs:
      image:
        type: string
        default: playground-latest
