name: Adapter Integration - Core v2
jobs:
  TestAdapter:
    strategy:
      fail-fast: false
      matrix:
        k8s_version:
        - v1.31.4
        - v1.32.0
    runs-on: ubuntu-24.04
    outputs:
      exitstatus: ${{ steps.runresources.outputs.exitstatus }}
    steps:
    - name: Set adapter_name for output
      id: adapter_name
      run: |
        USER_INPUT=${{ github.event.inputs.adapter_name }}
        echo "value=${USER_INPUT:-"meshery"}" >> $GITHUB_OUTPUT
    - name: Setting up minikube
      id: setk8s
      uses: manusa/actions-setup-minikube@v2.13.0
      with:
        minikube version: v1.34.0
        kubernetes version: ${{ matrix.k8s_version }}
        driver: docker
        start args: --cni "${{ inputs.k8s_cni }}"
    - name: Checkout Code
      uses: actions/checkout@master
    - name: Build the tagged Docker image
      run: "if [ \"${{ inputs.adapter_name }}\" != \"meshery\" ];then\n   eval $(minikube -p minikube docker-env) \n   docker build -t test:test .\nelse \n   eval $(minikube -p minikube docker-env) \n   docker build -f install/docker/Dockerfile -t test:test .           \nfi\n"
    - name: Retrieve kubeconfig
      run: |
        echo "Before flattening"
        cat ~/.kube/config
        kubectl config view --minify --flatten > ~/.kube/configtemp
        mv ~/.kube/configtemp ~/.kube/config
        echo "After flattening"
        cat ~/.kube/config
    - name: Setup meshery config and infinite token for use
      env:
        provider_token: ${{ secrets.token }}
      run: "echo $provider_token \nmkdir ~/.meshery\nconfig='{\"contexts\":{\"local\":{\"endpoint\":\"http://localhost:9081\",\"token\":\"default\",\"platform\":\"kubernetes\",\"components\":[],\"channel\":\"stable\",\"version\":\"latest\"}},\"current-context\":\"local\",\"tokens\":[{\"location\":\"auth.json\",\"name\":\"default\"}]}'\necho $config > ~/.meshery/config.yaml \ncat ~/.meshery/config.yaml\necho \"Using provider: ${{ inputs.provider }}\"\nif  [ \"${{ inputs.provider }}\" = \"Meshery\" ] && [ \"$provider_token\" != \"\" ] ;then\n  echo '{ \"meshery-provider\": \"Meshery\", \"token\": null }' | jq -c '.token = \"'$provider_token'\"' > ~/.meshery/auth.json\nelse\n  echo '{ \"meshery-provider\": \"None\", \"token\": \"\" }'  > ~/.meshery/auth.json\nfi\ncat ~/.meshery/auth.json\n"
    - name: Cluster info for debugging before starting Meshery
      run: kubectl get all -A
    - name: Start Meshery Server using mesheryctl
      run: |
        curl -L https://meshery.io/install | PLATFORM=kubernetes bash -
    - name: Start adapter
      run: "if [ \"${{ inputs.adapter_name }}\" != \"meshery\" ];then\n  touch testimagedep.yaml\n  curl ${{ inputs.deployment_url }} > ./testimagedep.yaml\n  yq e -i '.spec.template.spec.containers[0].image=\"test:test\"' ./testimagedep.yaml \n  yq e -i '.spec.template.spec.containers[0].imagePullPolicy=\"Never\"' ./testimagedep.yaml \n  cat testimagedep.yaml\n  kubectl apply -f testimagedep.yaml --namespace=meshery\n  kubectl apply -f ${{ inputs.service_url }} --namespace=meshery\nfi\n"
    - name: Start tunelling
      run: minikube tunnel &> /dev/null &
    - name: Check Meshery pod logs
      run: |
        SECONDS=0
        end=$((SECONDS+300))
        while [ $SECONDS -lt $end ]; do
            status=$(mesheryctl system  status -v | sed -n 2p | sed -e "s/[[:space:]]\+/ /g" |  cut -d " " -f 3)
            if [ "$status" = "Running" ];then
              break
            fi
        done
        mesheryctl system  logs meshery
    - name: Check if Meshery has been allotted external IP
      run: |
        svcstatus=$(kubectl get svc  -n meshery| grep meshery | tr -s ' ' | cut -d " " -f 4)
        echo $svcstatus
        if [ "$svcstatus" = "<pending>" ];then
           exit 1
        fi
    - name: Reset Meshery address
      run: "kubectl get svc -n meshery \nsvcip=\"http://$(kubectl get svc -n meshery | grep \"meshery \" | tr -s ' ' | cut -d \" \" -f 3):9081\"\necho \"this is $svcip\"\nconfig='{\"contexts\":{\"local\":{\"endpoint\":'$svcip',\"token\":\"default\",\"platform\":\"kubernetes\",\"adapters\":[],\"channel\":\"stable\",\"version\":\"latest\"}},\"current-context\":\"local\",\"tokens\":[{\"location\":\"auth.json\",\"name\":\"default\"}]}'\necho $config  > ~/.meshery/config.yaml\n"
    - name: Download patternfile
      uses: actions/download-artifact@v7
      with:
        name: patternfile
    - name: Wait for Meshery pods to come up
      run: sleep 100
    - name: Pattern apply
      run: |
        cat ./${{ inputs.patternfile_name }}
        mesheryctl design apply -f ./${{ inputs.patternfile_name }}
    - name: Sleep 120 seconds
      run: sleep 120
    - name: Pattern apply, second iteration. [IDEMPOTENT]
      run: |
        cat ./${{ inputs.patternfile_name }}
        mesheryctl design apply -f ./${{ inputs.patternfile_name }}
    - name: Check adapter logs
      run: |
        if [ "${{ inputs.adapter_name }}" != "meshery" ];then
          podname=$(kubectl get pods -n meshery | grep ${{ inputs.adapter_name }} | tr -s ' ' | cut -d " " -f 1)
          kubectl logs pod/$podname -n meshery
        fi
    - name: Check Meshery logs
      run: |
        mesheryctl system  logs meshery
    - name: Whole status for debugging
      run: kubectl get all -A
    - name: Check if all expected resources have started
      id: runresources
      run: "SECONDS=0\nexitstatus=0\nend=$((SECONDS+300))\nresourcenames=\"${{ inputs.expected_resources }}\"\nresourcetypes=\"${{ inputs.expected_resources_types }}\"\nnsnames=\"${{ inputs.expected_resources_namespaces}}\"\nset -f                      \nresources=(${resourcenames//,/ })\ntypes=(${resourcetypes//,/ })\nns=(${nsnames//,/ })\n\nbreakout=1\n\nwhile [ $SECONDS -lt $end ]; do\n    for i in \"${!resources[@]}\"\n    do\n        resourceinfo=$(kubectl get ${types[i]} -n ${ns[i]} | grep ${resources[i]} | tr -s ' ')\n        resourcestarted=$(echo $resourceinfo | cut -d \" \" -f 1)\n        resourcestatus=$(echo $resourceinfo | cut -d \" \" -f 3)\n        if [[ (\"${types[i]}\" = \"pod\" && \"$resourcestatus\" != \"Running\") || (\"${types[i]}\" != \"pod\" && \"$resourcestarted\" = \"\") ]];then\n          breakout=0\n        fi\n    done\n    if [ $breakout -eq 1 ];then\n      break\n    fi\n    breakout=1\ndone\ntouch data.json\nrunon=$(date)\nitran=0\nitdidnotrun=0\necho \"Ran on $runon\"\necho '{\"metadata\":{ \"k8s_version\":\"'${{ matrix.k8s_version }}'\", \"service_mesh_name\":\"'${{ inputs.adapter_name }}'\", \"service_mesh_version\":\"'${{ inputs.sm_version }}'\",\"adapter_version\":\"'${{ inputs.adapter_version }}'\" ,\"runon\":\"'$runon'\"}, \"resources_status\":{}, \"overall-status\":\"\"}' | jq > ./data.json\nfor i in \"${!resources[@]}\"\ndo\n  resourceinfo=$(kubectl get ${types[i]} -n ${ns[i]} | grep ${resources[i]} | tr -s ' ')\n  resourcestarted=$(echo $resourceinfo | cut -d \" \" -f 1)\n  resourcestatus=$(echo $resourceinfo | cut -d \" \" -f 3)\n  if [[ (\"${types[i]}\" = \"pod\" && \"$resourcestatus\" = \"Running\") || (\"${types[i]}\" != \"pod\" && \"$resourcestarted\" != \"\") ]];then\n    itran=1\n    echo \"${types[i]} ${resources[i]} started in namespace ${ns[i]}\"\n    echo $(jq '.resources_status.\"'${types[i]}/${resources[i]}'\" |=  \"Running\"' data.json) > data.json \n  else\n    itdidnotrun=1\n    echo \"${types[i]} ${resources[i]} did not start in namespace ${ns[i]} \"\n    echo $(jq '.resources_status.\"'${types[i]}/${resources[i]}'\" |=  \"Not Running\"' data.json) > data.json \n    exitstatus=1\n  fi\ndone\nstatus=\"\"\nif [ \"$exitstatus\" -eq 0 ];then\n    status=\"passing\"       \nelse \n    status=\"failing\"\nfi\nif [ \"$itran\" -eq 1 ] && [ \"$itdidnotrun\" -eq 1  ] ;then\n    status=\"partial\"\nfi\necho $(jq '.\"overall-status\" |=  \"'$status'\"' data.json) > data.json;     \nMESHERY_VERSION=$(curl -L -s https://github.com/meshery/meshery/releases/latest | grep -oP 'releases/tag/\\K[^\"]+' | grep -E '^v[0-9]+\\.[0-9]+\\.[0-9]+' | head -1)    \necho $(jq '.metadata.\"meshery-server-version\" |=\"'$MESHERY_VERSION'\"' data.json ) > data.json\necho \"exitstatus=$exitstatus\" >> $GITHUB_ENV\n"
    - name: UploadResults (Versioned)
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.output_filename }}-${{ matrix.k8s_version }}
        path: ./${{ inputs.output_filename }}
        overwrite: true
      continue-on-error: true
    - name: UploadResults (Legacy)
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.output_filename }}
        path: ./${{ inputs.output_filename }}
        overwrite: true
      continue-on-error: true
    - name: exit
      run: |
        if [ "$exitstatus" -eq 1 ];then
            exit 1
        fi
env:
  GERALT_SECRET: ${{ secrets.GERALT }}
on:
  workflow_call:
    inputs:
      expected_resources:
        required: true
        type: string
      expected_resources_types:
        required: true
        type: string
      expected_resources_namespaces:
        required: true
        type: string
      service_url:
        required: false
        type: string
      deployment_url:
        required: false
        type: string
      adapter_name:
        required: false
        type: string
        default: meshery
      patternfile_name:
        required: true
        type: string
      k8s_cni:
        required: false
        type: string
        default: bridge
      k8s_version:
        required: false
        type: string
      sm_version:
        required: false
        type: string
      output_filename:
        required: true
        type: string
      adapter_version:
        required: false
        type: string
      provider:
        required: false
        type: string
    secrets:
      token:
        required: true
